### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Schmazda** [MrNavaStar/Singularity#16]
Could you please add a license to this project? 
Some common licenses are explained here: https://choosealicense.com/
I would really love to use this in a project, but its currently not possible since this is technically "All Rights Reserved"

**Comment by Schmazda** [comment]
also a README file would be beneficial

**Comment by MrNavaStar** [comment]
This project is currently in development and unusable. The license is cc-zero, however feel to use the mod in any projects or anything. I really only take issue if you try to sell/promote my work as your own. 

I will add a read me and license once the project is released. 

Are you a developer or a user out of curiosity?

**Comment by Schmazda** [comment]
I'm a dev

**Comment by MrNavaStar** [comment]
Are you planning on using the sync api for some sort of mod integration or looking to use the internals? Is there some other api I could provide?

**Comment by Schmazda** [comment]
We would wanna use it to create a modded Minecraft server network using Velocity and Fabric.
Our goal is to sync the PlayerData across _some_ of our Fabric servers; some have to be not affected in our use case (e.g. Minigame servers) .
Also we are planning to use PostgreSQL to store all PlayerData so it would be very helpful if you could provide an option for that. 
Thanks!

**Comment by MrNavaStar** [comment]
Sounds cool! I've been spending this week on SQLib, the database backend for this project. Postgres is in the works! Hopefully I'll have something to show for it soon  here

**Comment by MrNavaStar** [comment]
License has been added
